from django.test import TestCase

# Create your tests here.
def discount_deal_by(self):
        return self.quantity * self.byproduct.discount_price_deal_shock()
    def price_by(self):
        return self.quantity*self.byproduct.price
    def discount_by(self):
        total_discount=0
        if self.item.program_valid():
            total_discount=self.quantity*self.product.price*(self.product.percent_discount/100)
        return total_discount
    def total_price(self):
        return self.price_by()-self.discount_deal_by()-self.discount_by()
# Generated by Django 3.2.4 on 2022-07-15 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20220712_0823'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Byproductcart',
        ),
    ]

    def get_image(self):
        image=self.item.get_image_cover()
        if self.product.color:
            if self.product.color.image:
                image=self.product.color.image.url
        return image